package com.bytes.ms_accounts.mappers;

import java.math.BigDecimal;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import com.bytes.ms_accounts.dtos.TransferReqestDTO;
import com.bytes.ms_accounts.dtos.TransferResponseDTO;
import com.bytes.ms_accounts.models.Transfer;

@Mapper(componentModel = "spring")
public interface TransferMapper {
    
    /**
     * Maps a Transfer entity to a TransferResponseDTO with beneficiary information.
     * 
     * Explicit mappings are used only for fields that require special handling:
     * - Nested property access (transfer.id -> transferId)
     * - Field name transformations (sourceAccountId -> sourceAccount)
    * - Complex calculations (amount + fee = totalDebit)
     * 
     * Other fields are mapped automatically by name matching.
     * 
     * @param transfer the Transfer entity to map
     * @param beneficiaryName the name of the transfer recipient (null if internal transfer)
     * @return a TransferResponseDTO containing all transfer details
     */
    @Mapping(target = "transferId", source = "transfer.id")
    @Mapping(target = "sourceAccount", source = "transfer.sourceAccountId")
    @Mapping(target = "totalDebit", expression = "java(transfer.getAmount().add(transfer.getFee() != null ? transfer.getFee() : java.math.BigDecimal.ZERO))")
    @Mapping(target = "timestamp", source = "transfer.createdAt")
    TransferResponseDTO toResponse(Transfer transfer, String beneficiaryName);

    /**
     * Maps a TransferRequestDTO to a Transfer entity with default values.
     * 
     * Auto-generated fields are set during entity creation:
     * - id: Generated by JPA (UUID)
     * - status: Initialized as PENDING
    * - fee: Calculated based on transfer amount
     * - createdAt: Set to current timestamp
     * - executedAt: Null until transfer is processed
     * 
     * @param transferReqestDTO the transfer request data
     * @return a new Transfer entity ready to be persisted
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "status", constant = "PENDING")
    @Mapping(target = "fee", expression = "java(fee != null ? fee : java.math.BigDecimal.ZERO)")
    @Mapping(target = "createdAt", expression = "java(java.time.Instant.now())")
    @Mapping(target = "executedAt", ignore = true)
    Transfer toEntity(TransferReqestDTO transferReqestDTO, BigDecimal fee);
}
