server:
  port: 8082

spring:
  application:
    name: ms-accounts
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

jwt:
  secret: ${JWT_SECRET_KEY:example-secret-key-for-testing}
  expiration: 86400
